### ISSUE TITLE
update wiki section on OS and systems settings that affect CPU scaling

### ISSUE THREAD

**Issue by daniel-dsouza** [starcitizen-lug/information-howtos#10]
Hello,

I modified the Performance Tuning page to add some more detailed information regarding CPU frequency scaling issues I had when playing Star Citizen. There doesn't seem to be a way to create a pull request for the wiki repo, so I included the fork here.

https://github.com/daniel-dsouza/psychic-octo-giggle/blob/master/Performance-Tuning.md

**Comment by the-sane** [comment]
Thanks a lot for this! At some point we want to move the wiki over to github pages so that folks can actually submit PRs against it. For now, this is perfect, thank you.

I tweaked it a bit before adding it. Let me know if it still makes sense:
https://github.com/starcitizen-lug/information-howtos/wiki/Performance-Tuning#changing-cpu-scaling-behavior-via-the-linux-kernel-and-system-management-bios

**Comment by daniel-dsouza** [comment]
wonderful, thanks!
