### ISSUE TITLE
TKG

### ISSUE THREAD

**Issue by antiwesley** [starcitizen-lug/information-howtos#7]
I've mentioned this before, but I think that the TKG option should be removed from the Helper until the TKG runners can be properly sourced. I'd hate to see people turning away from the game because they used that option and then there has been no updates since.

**Comment by the-sane** [comment]
Discussion on this is over here, let’s keep it in the right place:

https://github.com/starcitizen-lug/lug-helper/issues/38

Seems like it was a dependency issue that Termy has since resolved by adding some checks for zstd. If there are other issues besides that, please let us know over in that issue thread!
